/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttperrorsHttpErrorResponse {
    /// error message
    #[serde(rename = "message")]
    pub message: String,
    /// http status code
    #[serde(rename = "statuscode")]
    pub statuscode: i64,
}

impl HttperrorsHttpErrorResponse {
    pub fn new(message: String, statuscode: i64) -> HttperrorsHttpErrorResponse {
        HttperrorsHttpErrorResponse {
            message,
            statuscode,
        }
    }
}


