/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineAllocation {
    #[serde(rename = "boot_info", skip_serializing_if = "Option::is_none")]
    pub boot_info: Option<Box<crate::models::ModelsV1BootInfo>>,
    #[serde(rename = "console_password", skip_serializing_if = "Option::is_none")]
    pub console_password: Option<String>,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<Box<crate::models::ModelsV1ImageResponse>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "networks")]
    pub networks: Vec<crate::models::ModelsV1MachineNetwork>,
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "reinstall")]
    pub reinstall: bool,
    #[serde(rename = "ssh_pub_keys")]
    pub ssh_pub_keys: Vec<String>,
    #[serde(rename = "succeeded")]
    pub succeeded: bool,
    #[serde(rename = "user_data", skip_serializing_if = "Option::is_none")]
    pub user_data: Option<String>,
}

impl ModelsV1MachineAllocation {
    pub fn new(created: String, hostname: String, name: String, networks: Vec<crate::models::ModelsV1MachineNetwork>, project: String, reinstall: bool, ssh_pub_keys: Vec<String>, succeeded: bool) -> ModelsV1MachineAllocation {
        ModelsV1MachineAllocation {
            boot_info: None,
            console_password: None,
            created,
            description: None,
            hostname,
            image: None,
            name,
            networks,
            project,
            reinstall,
            ssh_pub_keys,
            succeeded,
            user_data: None,
        }
    }
}


