/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1IpResponse {
    #[serde(rename = "allocationuuid")]
    pub allocationuuid: String,
    #[serde(rename = "changed", skip_serializing_if = "Option::is_none")]
    pub changed: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "ipaddress")]
    pub ipaddress: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "networkid")]
    pub networkid: String,
    #[serde(rename = "projectid")]
    pub projectid: String,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "type")]
    pub _type: String,
}

impl ModelsV1IpResponse {
    pub fn new(allocationuuid: String, ipaddress: String, networkid: String, projectid: String, tags: Vec<String>, _type: String) -> ModelsV1IpResponse {
        ModelsV1IpResponse {
            allocationuuid,
            changed: None,
            created: None,
            description: None,
            ipaddress,
            name: None,
            networkid,
            projectid,
            tags,
            _type,
        }
    }
}


