/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineNetwork {
    #[serde(rename = "asn")]
    pub asn: i64,
    #[serde(rename = "destinationprefixes")]
    pub destinationprefixes: Vec<String>,
    #[serde(rename = "ips")]
    pub ips: Vec<String>,
    #[serde(rename = "nat")]
    pub nat: bool,
    #[serde(rename = "networkid")]
    pub networkid: String,
    #[serde(rename = "networktype")]
    pub networktype: String,
    #[serde(rename = "prefixes")]
    pub prefixes: Vec<String>,
    #[serde(rename = "private")]
    pub private: bool,
    #[serde(rename = "underlay")]
    pub underlay: bool,
    #[serde(rename = "vrf")]
    pub vrf: i64,
}

impl ModelsV1MachineNetwork {
    pub fn new(asn: i64, destinationprefixes: Vec<String>, ips: Vec<String>, nat: bool, networkid: String, networktype: String, prefixes: Vec<String>, private: bool, underlay: bool, vrf: i64) -> ModelsV1MachineNetwork {
        ModelsV1MachineNetwork {
            asn,
            destinationprefixes,
            ips,
            nat,
            networkid,
            networktype,
            prefixes,
            private,
            underlay,
            vrf,
        }
    }
}


