/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1PartitionBootConfiguration {
    #[serde(rename = "commandline", skip_serializing_if = "Option::is_none")]
    pub commandline: Option<String>,
    #[serde(rename = "imageurl", skip_serializing_if = "Option::is_none")]
    pub imageurl: Option<String>,
    #[serde(rename = "kernelurl", skip_serializing_if = "Option::is_none")]
    pub kernelurl: Option<String>,
}

impl ModelsV1PartitionBootConfiguration {
    pub fn new() -> ModelsV1PartitionBootConfiguration {
        ModelsV1PartitionBootConfiguration {
            commandline: None,
            imageurl: None,
            kernelurl: None,
        }
    }
}


