/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineBlockDevice {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partitions")]
    pub partitions: Vec<crate::models::ModelsV1MachineDiskPartition>,
    #[serde(rename = "primary")]
    pub primary: bool,
    #[serde(rename = "size")]
    pub size: i64,
}

impl ModelsV1MachineBlockDevice {
    pub fn new(name: String, partitions: Vec<crate::models::ModelsV1MachineDiskPartition>, primary: bool, size: i64) -> ModelsV1MachineBlockDevice {
        ModelsV1MachineBlockDevice {
            name,
            partitions,
            primary,
            size,
        }
    }
}


