/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineProvisioningEvent {
    #[serde(rename = "event")]
    pub event: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl ModelsV1MachineProvisioningEvent {
    pub fn new(event: String) -> ModelsV1MachineProvisioningEvent {
        ModelsV1MachineProvisioningEvent {
            event,
            message: None,
            time: None,
        }
    }
}


