/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1BootInfo {
    #[serde(rename = "bootloaderid")]
    pub bootloaderid: String,
    #[serde(rename = "cmdline")]
    pub cmdline: String,
    #[serde(rename = "image_id")]
    pub image_id: String,
    #[serde(rename = "initrd")]
    pub initrd: String,
    #[serde(rename = "kernel")]
    pub kernel: String,
    #[serde(rename = "os_partition")]
    pub os_partition: String,
    #[serde(rename = "primary_disk")]
    pub primary_disk: String,
}

impl ModelsV1BootInfo {
    pub fn new(bootloaderid: String, cmdline: String, image_id: String, initrd: String, kernel: String, os_partition: String, primary_disk: String) -> ModelsV1BootInfo {
        ModelsV1BootInfo {
            bootloaderid,
            cmdline,
            image_id,
            initrd,
            kernel,
            os_partition,
            primary_disk,
        }
    }
}


