/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineRecentProvisioningEvents {
    #[serde(rename = "incomplete_provisioning_cycles")]
    pub incomplete_provisioning_cycles: String,
    #[serde(rename = "last_event_time", skip_serializing_if = "Option::is_none")]
    pub last_event_time: Option<String>,
    #[serde(rename = "log")]
    pub log: Vec<crate::models::ModelsV1MachineProvisioningEvent>,
}

impl ModelsV1MachineRecentProvisioningEvents {
    pub fn new(incomplete_provisioning_cycles: String, log: Vec<crate::models::ModelsV1MachineProvisioningEvent>) -> ModelsV1MachineRecentProvisioningEvents {
        ModelsV1MachineRecentProvisioningEvents {
            incomplete_provisioning_cycles,
            last_event_time: None,
            log,
        }
    }
}


