/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineState {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl ModelsV1MachineState {
    pub fn new(description: String, value: String) -> ModelsV1MachineState {
        ModelsV1MachineState {
            description,
            value,
        }
    }
}


