/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineBios {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "vendor")]
    pub vendor: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl ModelsV1MachineBios {
    pub fn new(date: String, vendor: String, version: String) -> ModelsV1MachineBios {
        ModelsV1MachineBios {
            date,
            vendor,
            version,
        }
    }
}


