/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsV1MachineDiskPartition {
    #[serde(rename = "device")]
    pub device: String,
    #[serde(rename = "filesystem")]
    pub filesystem: String,
    #[serde(rename = "gptguid")]
    pub gptguid: String,
    #[serde(rename = "gpttyoe")]
    pub gpttyoe: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "mountoptions")]
    pub mountoptions: Vec<String>,
    #[serde(rename = "mountpoint")]
    pub mountpoint: String,
    #[serde(rename = "number")]
    pub number: i64,
    #[serde(rename = "properties")]
    pub properties: ::std::collections::HashMap<String, String>,
    #[serde(rename = "size")]
    pub size: i64,
}

impl ModelsV1MachineDiskPartition {
    pub fn new(device: String, filesystem: String, gptguid: String, gpttyoe: String, label: String, mountoptions: Vec<String>, mountpoint: String, number: i64, properties: ::std::collections::HashMap<String, String>, size: i64) -> ModelsV1MachineDiskPartition {
        ModelsV1MachineDiskPartition {
            device,
            filesystem,
            gptguid,
            gpttyoe,
            label,
            mountoptions,
            mountpoint,
            number,
            properties,
            size,
        }
    }
}


