/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ClusterFindRequest {
    #[serde(rename = "ID")]
    pub ID: String,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "PartitionID")]
    pub partition_id: String,
    #[serde(rename = "ProjectID")]
    pub project_id: String,
    #[serde(rename = "Tenant")]
    pub tenant: String,
}

impl V1ClusterFindRequest {
    pub fn new(ID: String, name: String, partition_id: String, project_id: String, tenant: String) -> V1ClusterFindRequest {
        V1ClusterFindRequest {
            ID,
            name,
            partition_id,
            project_id,
            tenant,
        }
    }
}


