/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ClusterUsageAccumuluated {
    /// the duration that this cluster is running
    #[serde(rename = "lifetime")]
    pub lifetime: i64,
}

impl V1ClusterUsageAccumuluated {
    pub fn new(lifetime: i64) -> V1ClusterUsageAccumuluated {
        V1ClusterUsageAccumuluated {
            lifetime,
        }
    }
}


