/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ClusterKubeconfigResponse {
    #[serde(rename = "Kubeconfig")]
    pub kubeconfig: String,
}

impl V1ClusterKubeconfigResponse {
    pub fn new(kubeconfig: String) -> V1ClusterKubeconfigResponse {
        V1ClusterKubeconfigResponse {
            kubeconfig,
        }
    }
}


