/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ContainerUsage {
    /// accounting annotations present on the last accounting report of this container
    #[serde(rename = "annotations")]
    pub annotations: Vec<String>,
    /// the cluster id of this container
    #[serde(rename = "clusterid")]
    pub clusterid: String,
    /// the cluster name of this container
    #[serde(rename = "clustername")]
    pub clustername: String,
    /// the container image of this container
    #[serde(rename = "containerimage")]
    pub containerimage: String,
    /// the name of this container
    #[serde(rename = "containername")]
    pub containername: String,
    /// the cpu seconds of this container (s*s)
    #[serde(rename = "cpuseconds")]
    pub cpuseconds: String,
    /// the duration that this container is running
    #[serde(rename = "lifetime")]
    pub lifetime: i64,
    /// the memory seconds of this container (byte*s)
    #[serde(rename = "memoryseconds")]
    pub memoryseconds: String,
    /// the namespace of this container
    #[serde(rename = "namespace")]
    pub namespace: String,
    /// the partition of this container
    #[serde(rename = "partition")]
    pub partition: String,
    /// the pod end time of this container
    #[serde(rename = "podend")]
    pub podend: String,
    /// the pod name of this container
    #[serde(rename = "podname")]
    pub podname: String,
    /// the pod start time of this container
    #[serde(rename = "podstart")]
    pub podstart: String,
    /// the pod uuid of this container
    #[serde(rename = "poduuid")]
    pub poduuid: String,
    /// the project id of this container
    #[serde(rename = "projectid")]
    pub projectid: String,
    /// the project name of this container
    #[serde(rename = "projectname")]
    pub projectname: String,
    /// the tenant of this container
    #[serde(rename = "tenant")]
    pub tenant: String,
    /// warnings that occurred when calculating the usage of this container
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
}

impl V1ContainerUsage {
    pub fn new(annotations: Vec<String>, clusterid: String, clustername: String, containerimage: String, containername: String, cpuseconds: String, lifetime: i64, memoryseconds: String, namespace: String, partition: String, podend: String, podname: String, podstart: String, poduuid: String, projectid: String, projectname: String, tenant: String, warnings: Vec<String>) -> V1ContainerUsage {
        V1ContainerUsage {
            annotations,
            clusterid,
            clustername,
            containerimage,
            containername,
            cpuseconds,
            lifetime,
            memoryseconds,
            namespace,
            partition,
            podend,
            podname,
            podstart,
            poduuid,
            projectid,
            projectname,
            tenant,
            warnings,
        }
    }
}


