/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ClusterResponse {
    #[serde(rename = "AdditionalNetworks")]
    pub additional_networks: Vec<String>,
    #[serde(rename = "ControlPlaneFeatureGates")]
    pub control_plane_feature_gates: Vec<String>,
    #[serde(rename = "CreationTimestamp")]
    pub creation_timestamp: String,
    #[serde(rename = "DNSEndpoint")]
    pub dns_endpoint: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "EgressRules")]
    pub egress_rules: Vec<crate::models::V1EgressRule>,
    #[serde(rename = "FirewallControllerVersion")]
    pub firewall_controller_version: String,
    #[serde(rename = "FirewallImage")]
    pub firewall_image: String,
    #[serde(rename = "FirewallSize")]
    pub firewall_size: String,
    #[serde(rename = "ID")]
    pub ID: String,
    #[serde(rename = "Kubernetes")]
    pub kubernetes: Box<crate::models::V1Kubernetes>,
    #[serde(rename = "Labels")]
    pub labels: ::std::collections::HashMap<String, String>,
    #[serde(rename = "Maintenance")]
    pub maintenance: Box<crate::models::V1Maintenance>,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Networking")]
    pub networking: Box<crate::models::V1Networking>,
    #[serde(rename = "PartitionID")]
    pub partition_id: String,
    #[serde(rename = "ProjectID")]
    pub project_id: String,
    #[serde(rename = "Purpose")]
    pub purpose: String,
    #[serde(rename = "Status")]
    pub status: Box<crate::models::V1beta1ShootStatus>,
    #[serde(rename = "Tenant")]
    pub tenant: String,
    #[serde(rename = "Workers")]
    pub workers: Vec<crate::models::V1Worker>,
    /// the firewalls which belong to this cluster
    #[serde(rename = "firewalls", skip_serializing_if = "Option::is_none")]
    pub firewalls: Option<Vec<crate::models::ModelsV1MachineResponse>>,
    /// the machines which belong to this cluster
    #[serde(rename = "machines", skip_serializing_if = "Option::is_none")]
    pub machines: Option<Vec<crate::models::ModelsV1MachineResponse>>,
}

impl V1ClusterResponse {
    pub fn new(additional_networks: Vec<String>, control_plane_feature_gates: Vec<String>, creation_timestamp: String, dns_endpoint: String, description: String, egress_rules: Vec<crate::models::V1EgressRule>, firewall_controller_version: String, firewall_image: String, firewall_size: String, ID: String, kubernetes: crate::models::V1Kubernetes, labels: ::std::collections::HashMap<String, String>, maintenance: crate::models::V1Maintenance, name: String, networking: crate::models::V1Networking, partition_id: String, project_id: String, purpose: String, status: crate::models::V1beta1ShootStatus, tenant: String, workers: Vec<crate::models::V1Worker>) -> V1ClusterResponse {
        V1ClusterResponse {
            additional_networks,
            control_plane_feature_gates,
            creation_timestamp,
            dns_endpoint,
            description,
            egress_rules,
            firewall_controller_version,
            firewall_image,
            firewall_size,
            ID,
            kubernetes: Box::new(kubernetes),
            labels,
            maintenance: Box::new(maintenance),
            name,
            networking: Box::new(networking),
            partition_id,
            project_id,
            purpose,
            status: Box::new(status),
            tenant,
            workers,
            firewalls: None,
            machines: None,
        }
    }
}


