/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ContainerUsageAccumuluated {
    /// the accumuluated cpu seconds of the containers in this response (s*s)
    #[serde(rename = "cpuseconds")]
    pub cpuseconds: String,
    /// the duration that this container is running
    #[serde(rename = "lifetime")]
    pub lifetime: i64,
    /// the accumulated memory seconds of the containers in this response (byte*s)
    #[serde(rename = "memoryseconds")]
    pub memoryseconds: String,
}

impl V1ContainerUsageAccumuluated {
    pub fn new(cpuseconds: String, lifetime: i64, memoryseconds: String) -> V1ContainerUsageAccumuluated {
        V1ContainerUsageAccumuluated {
            cpuseconds,
            lifetime,
            memoryseconds,
        }
    }
}


