/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ClusterCredentialsResponse {
    #[serde(rename = "Kubeconfig")]
    pub kubeconfig: String,
    #[serde(rename = "SSHKeyPair")]
    pub ssh_key_pair: Box<crate::models::V1SshKeyPair>,
}

impl V1ClusterCredentialsResponse {
    pub fn new(kubeconfig: String, ssh_key_pair: crate::models::V1SshKeyPair) -> V1ClusterCredentialsResponse {
        V1ClusterCredentialsResponse {
            kubeconfig,
            ssh_key_pair: Box::new(ssh_key_pair),
        }
    }
}


