/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ClusterReconcileRequest {
    /// the gardener shoot operation annotation to annotate the shoot with
    #[serde(rename = "operation")]
    pub operation: String,
}

impl V1ClusterReconcileRequest {
    pub fn new(operation: String) -> V1ClusterReconcileRequest {
        V1ClusterReconcileRequest {
            operation,
        }
    }
}


