/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1EgressRule {
    #[serde(rename = "IPs")]
    pub ips: Vec<String>,
    #[serde(rename = "NetworkID")]
    pub network_id: String,
}

impl V1EgressRule {
    pub fn new(ips: Vec<String>, network_id: String) -> V1EgressRule {
        V1EgressRule {
            ips,
            network_id,
        }
    }
}


