/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1IpFindRequest {
    #[serde(rename = "IPAddress")]
    pub ip_address: String,
    #[serde(rename = "MachineID")]
    pub machine_id: String,
    #[serde(rename = "NetworkID")]
    pub network_id: String,
    #[serde(rename = "ParentPrefixCidr")]
    pub parent_prefix_cidr: String,
    #[serde(rename = "ProjectID")]
    pub project_id: String,
    #[serde(rename = "Tags")]
    pub tags: Vec<String>,
    #[serde(rename = "Type")]
    pub _type: String,
}

impl V1IpFindRequest {
    pub fn new(ip_address: String, machine_id: String, network_id: String, parent_prefix_cidr: String, project_id: String, tags: Vec<String>, _type: String) -> V1IpFindRequest {
        V1IpFindRequest {
            ip_address,
            machine_id,
            network_id,
            parent_prefix_cidr,
            project_id,
            tags,
            _type,
        }
    }
}


