/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1IpAllocateRequest {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "ipaddress")]
    pub ipaddress: String,
    #[serde(rename = "machineid")]
    pub machineid: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "networkid")]
    pub networkid: String,
    #[serde(rename = "projectid")]
    pub projectid: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl V1IpAllocateRequest {
    pub fn new(ipaddress: String, machineid: String, networkid: String, projectid: String) -> V1IpAllocateRequest {
        V1IpAllocateRequest {
            description: None,
            ipaddress,
            machineid,
            name: None,
            networkid,
            projectid,
            tags: None,
            _type: None,
        }
    }
}


