/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Kubernetes {
    #[serde(rename = "AllowPrivilegedContainers")]
    pub allow_privileged_containers: bool,
    #[serde(rename = "ExpirationDate")]
    pub expiration_date: String,
    #[serde(rename = "Version")]
    pub version: String,
}

impl V1Kubernetes {
    pub fn new(allow_privileged_containers: bool, expiration_date: String, version: String) -> V1Kubernetes {
        V1Kubernetes {
            allow_privileged_containers,
            expiration_date,
            version,
        }
    }
}


