/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Maintenance {
    #[serde(rename = "AutoUpdate")]
    pub auto_update: Box<crate::models::V1MaintenanceAutoUpdate>,
    #[serde(rename = "TimeWindow")]
    pub time_window: Box<crate::models::V1MaintenanceTimeWindow>,
}

impl V1Maintenance {
    pub fn new(auto_update: crate::models::V1MaintenanceAutoUpdate, time_window: crate::models::V1MaintenanceTimeWindow) -> V1Maintenance {
        V1Maintenance {
            auto_update: Box::new(auto_update),
            time_window: Box::new(time_window),
        }
    }
}


