/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MaintenanceAutoUpdate {
    #[serde(rename = "KubernetesVersion")]
    pub kubernetes_version: bool,
    #[serde(rename = "MachineImage")]
    pub machine_image: bool,
}

impl V1MaintenanceAutoUpdate {
    pub fn new(kubernetes_version: bool, machine_image: bool) -> V1MaintenanceAutoUpdate {
        V1MaintenanceAutoUpdate {
            kubernetes_version,
            machine_image,
        }
    }
}


