/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MaintenanceTimeWindow {
    #[serde(rename = "Begin")]
    pub begin: String,
    #[serde(rename = "End")]
    pub end: String,
}

impl V1MaintenanceTimeWindow {
    pub fn new(begin: String, end: String) -> V1MaintenanceTimeWindow {
        V1MaintenanceTimeWindow {
            begin,
            end,
        }
    }
}


