/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MasterdataLookupRequest {
    /// lookup by clusterID as returned by cloud-api (e.g. 345abc12-3321-4dbc-8d17-55c6ea4fcb38)
    #[serde(rename = "cluster_id", skip_serializing_if = "Option::is_none")]
    pub cluster_id: Option<String>,
    #[serde(rename = "cluster_name_project", skip_serializing_if = "Option::is_none")]
    pub cluster_name_project: Option<Box<crate::models::V1ClusterNameProject>>,
    #[serde(rename = "project_id_time", skip_serializing_if = "Option::is_none")]
    pub project_id_time: Option<Box<crate::models::V1ProjectIdTime>>,
}

impl V1MasterdataLookupRequest {
    pub fn new() -> V1MasterdataLookupRequest {
        V1MasterdataLookupRequest {
            cluster_id: None,
            cluster_name_project: None,
            project_id_time: None,
        }
    }
}


