/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1NetworkUsageAccumuluated {
    /// the accumuluated ingoing traffic (byte)
    #[serde(rename = "in")]
    pub _in: String,
    /// the duration for that the network usage is accounted
    #[serde(rename = "lifetime")]
    pub lifetime: i64,
    /// the accumulated outgoing traffic (byte)
    #[serde(rename = "out")]
    pub out: String,
    /// the accumulated total traffic (byte)
    #[serde(rename = "total")]
    pub total: String,
}

impl V1NetworkUsageAccumuluated {
    pub fn new(_in: String, lifetime: i64, out: String, total: String) -> V1NetworkUsageAccumuluated {
        V1NetworkUsageAccumuluated {
            _in,
            lifetime,
            out,
            total,
        }
    }
}


