/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Networking {
    #[serde(rename = "Nodes")]
    pub nodes: String,
    #[serde(rename = "Pods")]
    pub pods: String,
    #[serde(rename = "Services")]
    pub services: String,
    #[serde(rename = "Type")]
    pub _type: String,
}

impl V1Networking {
    pub fn new(nodes: String, pods: String, services: String, _type: String) -> V1Networking {
        V1Networking {
            nodes,
            pods,
            services,
            _type,
        }
    }
}


