/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ProjectListResponse {
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<crate::models::V1ProjectResponse>>,
}

impl V1ProjectListResponse {
    pub fn new() -> V1ProjectListResponse {
        V1ProjectListResponse {
            projects: None,
        }
    }
}


