/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ProjectIdTime {
    /// projectID as returned by cloud-api (e.g. 10241dd7-a8de-4856-8ac0-b55830b22036)
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// point in time
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl V1ProjectIdTime {
    pub fn new() -> V1ProjectIdTime {
        V1ProjectIdTime {
            project_id: None,
            time: None,
        }
    }
}


