/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1S3Usage {
    /// the bucket id of this s3 bucket
    #[serde(rename = "bucketid")]
    pub bucketid: String,
    /// the bucket name of this s3 bucket
    #[serde(rename = "bucketname")]
    pub bucketname: String,
    /// the last reported number of objects of this s3 bucket
    #[serde(rename = "currentnumberofobjects")]
    pub currentnumberofobjects: String,
    /// the last reported size of this s3 bucket
    #[serde(rename = "currentsize")]
    pub currentsize: String,
    /// the end time of this s3 bucket
    #[serde(rename = "end")]
    pub end: String,
    /// the duration that this s3 bucket is running
    #[serde(rename = "lifetime")]
    pub lifetime: i64,
    /// the partition of this s3 bucket
    #[serde(rename = "partition")]
    pub partition: String,
    /// the project id of this s3 bucket
    #[serde(rename = "projectid")]
    pub projectid: String,
    /// the project name of this s3 bucket
    #[serde(rename = "projectname")]
    pub projectname: String,
    /// the start time of this s3 bucket
    #[serde(rename = "start")]
    pub start: String,
    /// the storage seconds of this s3 bucket (byte*s)
    #[serde(rename = "storageseconds")]
    pub storageseconds: String,
    /// the tenant of this s3 bucket
    #[serde(rename = "tenant")]
    pub tenant: String,
    /// the user name of this s3 bucket
    #[serde(rename = "user")]
    pub user: String,
    /// warnings that occurred when calculating the usage of this s3 bucket
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
}

impl V1S3Usage {
    pub fn new(bucketid: String, bucketname: String, currentnumberofobjects: String, currentsize: String, end: String, lifetime: i64, partition: String, projectid: String, projectname: String, start: String, storageseconds: String, tenant: String, user: String, warnings: Vec<String>) -> V1S3Usage {
        V1S3Usage {
            bucketid,
            bucketname,
            currentnumberofobjects,
            currentsize,
            end,
            lifetime,
            partition,
            projectid,
            projectname,
            start,
            storageseconds,
            tenant,
            user,
            warnings,
        }
    }
}


