/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1S3CredentialsResponse {
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "keys")]
    pub keys: Vec<crate::models::V1S3Key>,
    #[serde(rename = "max_buckets")]
    pub max_buckets: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partition")]
    pub partition: String,
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "tenant")]
    pub tenant: String,
}

impl V1S3CredentialsResponse {
    pub fn new(endpoint: String, id: String, keys: Vec<crate::models::V1S3Key>, max_buckets: i64, name: String, partition: String, project: String, tenant: String) -> V1S3CredentialsResponse {
        V1S3CredentialsResponse {
            endpoint,
            id,
            keys,
            max_buckets,
            name,
            partition,
            project,
            tenant,
        }
    }
}


