/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1S3UpdateRequest {
    #[serde(rename = "add_keys")]
    pub add_keys: Vec<crate::models::V1S3Key>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "partition")]
    pub partition: String,
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "remove_access_keys")]
    pub remove_access_keys: Vec<String>,
    #[serde(rename = "tenant")]
    pub tenant: String,
}

impl V1S3UpdateRequest {
    pub fn new(add_keys: Vec<crate::models::V1S3Key>, id: String, partition: String, project: String, remove_access_keys: Vec<String>, tenant: String) -> V1S3UpdateRequest {
        V1S3UpdateRequest {
            add_keys,
            id,
            partition,
            project,
            remove_access_keys,
            tenant,
        }
    }
}


