/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ShootConstraints {
    /// the list of available firewall images
    #[serde(rename = "firewall_images")]
    pub firewall_images: Vec<String>,
    /// the list of available firewall types
    #[serde(rename = "firewall_types")]
    pub firewall_types: Vec<String>,
    /// the list of available kubernetes versions
    #[serde(rename = "kubernetes_versions")]
    pub kubernetes_versions: Vec<String>,
    /// the list of available machine images
    #[serde(rename = "machine_images")]
    pub machine_images: Vec<crate::models::V1MachineImage>,
    /// the list of available machine types
    #[serde(rename = "machine_types")]
    pub machine_types: Vec<String>,
    /// the list of available networks for cluster creation
    #[serde(rename = "networks")]
    pub networks: Vec<String>,
    /// the list of available partitions
    #[serde(rename = "partitions")]
    pub partitions: Vec<String>,
}

impl V1ShootConstraints {
    pub fn new(firewall_images: Vec<String>, firewall_types: Vec<String>, kubernetes_versions: Vec<String>, machine_images: Vec<crate::models::V1MachineImage>, machine_types: Vec<String>, networks: Vec<String>, partitions: Vec<String>) -> V1ShootConstraints {
        V1ShootConstraints {
            firewall_images,
            firewall_types,
            kubernetes_versions,
            machine_images,
            machine_types,
            networks,
            partitions,
        }
    }
}


