/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Tenant {
    #[serde(rename = "default_quotas", skip_serializing_if = "Option::is_none")]
    pub default_quotas: Option<Box<crate::models::V1QuotaSet>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::V1Meta>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "quotas", skip_serializing_if = "Option::is_none")]
    pub quotas: Option<Box<crate::models::V1QuotaSet>>,
}

impl V1Tenant {
    pub fn new() -> V1Tenant {
        V1Tenant {
            default_quotas: None,
            description: None,
            meta: None,
            name: None,
            quotas: None,
        }
    }
}


