/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1VolumeUsageAccumuluated {
    /// the accumulated capacity seconds of the volumes in this response (byte*s)
    #[serde(rename = "capacityseconds")]
    pub capacityseconds: String,
    /// the duration that this volume is running
    #[serde(rename = "lifetime")]
    pub lifetime: i64,
}

impl V1VolumeUsageAccumuluated {
    pub fn new(capacityseconds: String, lifetime: i64) -> V1VolumeUsageAccumuluated {
        V1VolumeUsageAccumuluated {
            capacityseconds,
            lifetime,
        }
    }
}


