/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1Condition {
    #[serde(rename = "codes", skip_serializing_if = "Option::is_none")]
    pub codes: Option<Vec<String>>,
    #[serde(rename = "lastTransitionTime")]
    pub last_transition_time: String,
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1beta1Condition {
    pub fn new(last_transition_time: String, last_update_time: String, message: String, reason: String, status: String, _type: String) -> V1beta1Condition {
        V1beta1Condition {
            codes: None,
            last_transition_time,
            last_update_time,
            message,
            reason,
            status,
            _type,
        }
    }
}


