/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1ShootStatus {
    #[serde(rename = "clusterIdentity", skip_serializing_if = "Option::is_none")]
    pub cluster_identity: Option<String>,
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V1beta1Condition>>,
    #[serde(rename = "constraints", skip_serializing_if = "Option::is_none")]
    pub constraints: Option<Vec<crate::models::V1beta1Condition>>,
    #[serde(rename = "gardener")]
    pub gardener: Box<crate::models::V1beta1Gardener>,
    #[serde(rename = "hibernated")]
    pub hibernated: bool,
    #[serde(rename = "lastErrors", skip_serializing_if = "Option::is_none")]
    pub last_errors: Option<Vec<crate::models::V1beta1LastError>>,
    #[serde(rename = "lastOperation", skip_serializing_if = "Option::is_none")]
    pub last_operation: Option<Box<crate::models::V1beta1LastOperation>>,
    #[serde(rename = "observedGeneration", skip_serializing_if = "Option::is_none")]
    pub observed_generation: Option<i64>,
    #[serde(rename = "retryCycleStartTime", skip_serializing_if = "Option::is_none")]
    pub retry_cycle_start_time: Option<String>,
    #[serde(rename = "seedName", skip_serializing_if = "Option::is_none")]
    pub seed_name: Option<String>,
    #[serde(rename = "technicalID")]
    pub technical_id: String,
    #[serde(rename = "uid")]
    pub uid: String,
}

impl V1beta1ShootStatus {
    pub fn new(gardener: crate::models::V1beta1Gardener, hibernated: bool, technical_id: String, uid: String) -> V1beta1ShootStatus {
        V1beta1ShootStatus {
            cluster_identity: None,
            conditions: None,
            constraints: None,
            gardener: Box::new(gardener),
            hibernated,
            last_errors: None,
            last_operation: None,
            observed_generation: None,
            retry_cycle_start_time: None,
            seed_name: None,
            technical_id,
            uid,
        }
    }
}


