/*
 * cloud-api
 *
 * Resource for managing cloud entities
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devops@f-i-ts.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1LastOperation {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "lastUpdateTime")]
    pub last_update_time: String,
    #[serde(rename = "progress")]
    pub progress: i64,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1beta1LastOperation {
    pub fn new(description: String, last_update_time: String, progress: i64, state: String, _type: String) -> V1beta1LastOperation {
        V1beta1LastOperation {
            description,
            last_update_time,
            progress,
            state,
            _type,
        }
    }
}


